version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  rabbitmq_data:

services: 
  postgresql:
    image: postgis/postgis:16-3.4
    hostname: postgresql
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ridehail_user
      POSTGRES_PASSWORD: ridehail_pass
      POSTGRES_DB: ridehail_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ridehail_user -d ridehail_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - net
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://ridehail_user:ridehail_pass@postgresql:5432/ridehail_db?sslmode=disable",
        "up"
      ]
    depends_on:
      postgresql:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    networks:
      - net
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping && nc -z localhost 5672"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Services

  driver-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ridehail/driver-service:latest
    networks:
      - net
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["./main", "--mode=driver-service"]
    ports:
      - "3001:3001"  
    restart: unless-stopped

  admin-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ridehail/admin-service:latest
    networks:
      - net
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["./main", "--mode=admin-service"]
    ports:
      - "3004:3004"
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ridehail/auth-service:latest
    networks:
      - net
    depends_on:
      postgresql:
        condition: service_healthy
    command: ["./main", "--mode=auth-service"]
    ports:
      - "3005:3005"
    restart: unless-stopped

  ride-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ridehail/ride-service:latest
    networks:
      - net
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: ["./main", "--mode=ride-service"]
    ports:
      - "3000:3000"
    restart: unless-stopped